// flow-typed signature: d0c29d5fab5a31c6bb97b6f515e1a675
// flow-typed version: <<STUB>>/@meetup/swarm-components_v0.6.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@meetup/swarm-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@meetup/swarm-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@meetup/swarm-components/lib/Button' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/Checkbox' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/FieldHelper' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/FieldLabel' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/Icon' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/index' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/LinkButton' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/NumericalInput' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/Radio' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/Select' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/Textarea' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/TextInput' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/Toggle' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/TogglePill' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/utils/buttonUtils' {
  declare module.exports: any;
}

declare module '@meetup/swarm-components/lib/utils/designConstants' {
  declare module.exports: any;
}

// Filename aliases
declare module '@meetup/swarm-components/lib/Button.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/Button'>;
}
declare module '@meetup/swarm-components/lib/Checkbox.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/Checkbox'>;
}
declare module '@meetup/swarm-components/lib/FieldHelper.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/FieldHelper'>;
}
declare module '@meetup/swarm-components/lib/FieldLabel.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/FieldLabel'>;
}
declare module '@meetup/swarm-components/lib/Icon.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/Icon'>;
}
declare module '@meetup/swarm-components/lib/index.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/index'>;
}
declare module '@meetup/swarm-components/lib/LinkButton.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/LinkButton'>;
}
declare module '@meetup/swarm-components/lib/NumericalInput.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/NumericalInput'>;
}
declare module '@meetup/swarm-components/lib/Radio.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/Radio'>;
}
declare module '@meetup/swarm-components/lib/Select.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/Select'>;
}
declare module '@meetup/swarm-components/lib/Textarea.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/Textarea'>;
}
declare module '@meetup/swarm-components/lib/TextInput.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/TextInput'>;
}
declare module '@meetup/swarm-components/lib/Toggle.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/Toggle'>;
}
declare module '@meetup/swarm-components/lib/TogglePill.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/TogglePill'>;
}
declare module '@meetup/swarm-components/lib/utils/buttonUtils.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/utils/buttonUtils'>;
}
declare module '@meetup/swarm-components/lib/utils/designConstants.js' {
  declare module.exports: $Exports<'@meetup/swarm-components/lib/utils/designConstants'>;
}
