// flow-typed signature: 3df0ff97861e61cdde3d3addc4a909b6
// flow-typed version: <<STUB>>/@meetup/swarm-styles_v0.2.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@meetup/swarm-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@meetup/swarm-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@meetup/swarm-styles/lib/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module '@meetup/swarm-styles/lib/styles.js' {
  declare module.exports: $Exports<'@meetup/swarm-styles/lib/styles'>;
}
