// flow-typed signature: 17b5486d1f33cd9b6f6fc1242bab7d7c
// flow-typed version: <<STUB>>/eslint-plugin-meetup_v1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-meetup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-meetup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-meetup/lib/rules/trn' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meetup/tests/lib/rules/trn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-meetup/index' {
  declare module.exports: $Exports<'eslint-plugin-meetup'>;
}
declare module 'eslint-plugin-meetup/index.js' {
  declare module.exports: $Exports<'eslint-plugin-meetup'>;
}
declare module 'eslint-plugin-meetup/lib/rules/trn.js' {
  declare module.exports: $Exports<'eslint-plugin-meetup/lib/rules/trn'>;
}
declare module 'eslint-plugin-meetup/tests/lib/rules/trn.js' {
  declare module.exports: $Exports<'eslint-plugin-meetup/tests/lib/rules/trn'>;
}
