// flow-typed signature: 1786aae8eef34e05549f89efaf34d4a5
// flow-typed version: <<STUB>>/meetup-web-mocks_v1.0.262/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'meetup-web-mocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'meetup-web-mocks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'meetup-web-mocks/lib/api' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/lib/app' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/lib/group/communication/api' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/lib/group/communication/app' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/lib/notifications/api' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/lib/reactIntl' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/src/api' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/src/app' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/src/group/communication/api' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/src/group/communication/app' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/src/notifications/api' {
  declare module.exports: any;
}

declare module 'meetup-web-mocks/src/reactIntl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'meetup-web-mocks/lib/api.js' {
  declare module.exports: $Exports<'meetup-web-mocks/lib/api'>;
}
declare module 'meetup-web-mocks/lib/app.js' {
  declare module.exports: $Exports<'meetup-web-mocks/lib/app'>;
}
declare module 'meetup-web-mocks/lib/group/communication/api.js' {
  declare module.exports: $Exports<'meetup-web-mocks/lib/group/communication/api'>;
}
declare module 'meetup-web-mocks/lib/group/communication/app.js' {
  declare module.exports: $Exports<'meetup-web-mocks/lib/group/communication/app'>;
}
declare module 'meetup-web-mocks/lib/notifications/api.js' {
  declare module.exports: $Exports<'meetup-web-mocks/lib/notifications/api'>;
}
declare module 'meetup-web-mocks/lib/reactIntl.js' {
  declare module.exports: $Exports<'meetup-web-mocks/lib/reactIntl'>;
}
declare module 'meetup-web-mocks/src/api.js' {
  declare module.exports: $Exports<'meetup-web-mocks/src/api'>;
}
declare module 'meetup-web-mocks/src/app.js' {
  declare module.exports: $Exports<'meetup-web-mocks/src/app'>;
}
declare module 'meetup-web-mocks/src/group/communication/api.js' {
  declare module.exports: $Exports<'meetup-web-mocks/src/group/communication/api'>;
}
declare module 'meetup-web-mocks/src/group/communication/app.js' {
  declare module.exports: $Exports<'meetup-web-mocks/src/group/communication/app'>;
}
declare module 'meetup-web-mocks/src/notifications/api.js' {
  declare module.exports: $Exports<'meetup-web-mocks/src/notifications/api'>;
}
declare module 'meetup-web-mocks/src/reactIntl.js' {
  declare module.exports: $Exports<'meetup-web-mocks/src/reactIntl'>;
}
