// flow-typed signature: 4dac42b6df0a53b166b2b5d240b68725
// flow-typed version: <<STUB>>/mwp-config_v16.0.2422/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mwp-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mwp-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mwp-config/babel/index' {
  declare module.exports: any;
}

declare module 'mwp-config/env' {
  declare module.exports: any;
}

declare module 'mwp-config/locales' {
  declare module.exports: any;
}

declare module 'mwp-config/localesSecondary' {
  declare module.exports: any;
}

declare module 'mwp-config/package' {
  declare module.exports: any;
}

declare module 'mwp-config/paths' {
  declare module.exports: any;
}

declare module 'mwp-config/server/index' {
  declare module.exports: any;
}

declare module 'mwp-config/server/index.test' {
  declare module.exports: any;
}

declare module 'mwp-config/server/util' {
  declare module.exports: any;
}

declare module 'mwp-config/stylelint/stylelint-config-base' {
  declare module.exports: any;
}

declare module 'mwp-config/stylelint/stylelint-config-order' {
  declare module.exports: any;
}

declare module 'mwp-config/stylelint/stylelint-config-scss' {
  declare module.exports: any;
}

declare module 'mwp-config/stylelint/stylelint-config-swarmProject' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mwp-config/babel/index.js' {
  declare module.exports: $Exports<'mwp-config/babel/index'>;
}
declare module 'mwp-config/env.js' {
  declare module.exports: $Exports<'mwp-config/env'>;
}
declare module 'mwp-config/index' {
  declare module.exports: $Exports<'mwp-config'>;
}
declare module 'mwp-config/index.js' {
  declare module.exports: $Exports<'mwp-config'>;
}
declare module 'mwp-config/locales.js' {
  declare module.exports: $Exports<'mwp-config/locales'>;
}
declare module 'mwp-config/localesSecondary.js' {
  declare module.exports: $Exports<'mwp-config/localesSecondary'>;
}
declare module 'mwp-config/package.js' {
  declare module.exports: $Exports<'mwp-config/package'>;
}
declare module 'mwp-config/paths.js' {
  declare module.exports: $Exports<'mwp-config/paths'>;
}
declare module 'mwp-config/server/index.js' {
  declare module.exports: $Exports<'mwp-config/server/index'>;
}
declare module 'mwp-config/server/index.test.js' {
  declare module.exports: $Exports<'mwp-config/server/index.test'>;
}
declare module 'mwp-config/server/util.js' {
  declare module.exports: $Exports<'mwp-config/server/util'>;
}
declare module 'mwp-config/stylelint/stylelint-config-base.js' {
  declare module.exports: $Exports<'mwp-config/stylelint/stylelint-config-base'>;
}
declare module 'mwp-config/stylelint/stylelint-config-order.js' {
  declare module.exports: $Exports<'mwp-config/stylelint/stylelint-config-order'>;
}
declare module 'mwp-config/stylelint/stylelint-config-scss.js' {
  declare module.exports: $Exports<'mwp-config/stylelint/stylelint-config-scss'>;
}
declare module 'mwp-config/stylelint/stylelint-config-swarmProject.js' {
  declare module.exports: $Exports<'mwp-config/stylelint/stylelint-config-swarmProject'>;
}
