// flow-typed signature: 5086f9f8f5f9ae49cecfa6736493e354
// flow-typed version: <<STUB>>/mwp-i18n_v21.0.2897/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mwp-i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mwp-i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mwp-i18n/lib/loadLocaleData' {
  declare module.exports: any;
}

declare module 'mwp-i18n/lib/localizedLanguageMap' {
  declare module.exports: any;
}

declare module 'mwp-i18n/lib/withIntl' {
  declare module.exports: any;
}

declare module 'mwp-i18n/src/loadLocaleData' {
  declare module.exports: any;
}

declare module 'mwp-i18n/src/loadLocaleData.test' {
  declare module.exports: any;
}

declare module 'mwp-i18n/src/localizedLanguageMap' {
  declare module.exports: any;
}

declare module 'mwp-i18n/src/localizedLanguageMap.test' {
  declare module.exports: any;
}

declare module 'mwp-i18n/src/withIntl' {
  declare module.exports: any;
}

declare module 'mwp-i18n/src/withIntl.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mwp-i18n/lib/loadLocaleData.js' {
  declare module.exports: $Exports<'mwp-i18n/lib/loadLocaleData'>;
}
declare module 'mwp-i18n/lib/localizedLanguageMap.js' {
  declare module.exports: $Exports<'mwp-i18n/lib/localizedLanguageMap'>;
}
declare module 'mwp-i18n/lib/withIntl.js' {
  declare module.exports: $Exports<'mwp-i18n/lib/withIntl'>;
}
declare module 'mwp-i18n/src/loadLocaleData.js' {
  declare module.exports: $Exports<'mwp-i18n/src/loadLocaleData'>;
}
declare module 'mwp-i18n/src/loadLocaleData.test.js' {
  declare module.exports: $Exports<'mwp-i18n/src/loadLocaleData.test'>;
}
declare module 'mwp-i18n/src/localizedLanguageMap.js' {
  declare module.exports: $Exports<'mwp-i18n/src/localizedLanguageMap'>;
}
declare module 'mwp-i18n/src/localizedLanguageMap.test.js' {
  declare module.exports: $Exports<'mwp-i18n/src/localizedLanguageMap.test'>;
}
declare module 'mwp-i18n/src/withIntl.jsx' {
  declare module.exports: $Exports<'mwp-i18n/src/withIntl'>;
}
declare module 'mwp-i18n/src/withIntl.test.jsx' {
  declare module.exports: $Exports<'mwp-i18n/src/withIntl.test'>;
}
