// flow-typed signature: dbad08e82ab9a5b76fe1d5c6a09efa8e
// flow-typed version: <<STUB>>/mwp-app-render_v21.0.2897/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mwp-app-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mwp-app-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mwp-app-render/lib/components/BrowserApp' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/connectWithMatchMedia' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/Dom' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/PageWrap/index' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/SEOHead' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/ServerApp' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/shared/PlatformApp' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/shared/ServiceWorker' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/StateBroadcast' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/StyleWith' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/uxcapture/UXCapture' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureCreate' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureFont' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureImageLoad' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureInlineMark' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureInteractiveMark' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureStartView' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/util/browserPolyfill' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/util/dateTimeUtils' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/util/googleTagManager' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/util/seo/ldJson' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/util/seo/links' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/util/seo/metaTags' {
  declare module.exports: any;
}

declare module 'mwp-app-render/lib/util/socialHelper' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/BrowserApp' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/BrowserApp.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/connectWithMatchMedia' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/connectWithMatchMedia.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/Dom' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/Dom.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/PageWrap/index' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/PageWrap/index.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/SEOHead' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/seoHead.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/ServerApp' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/ServerApp.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/shared/PlatformApp' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/shared/ServiceWorker' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/StateBroadcast' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/stateBroadcast.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/StyleWith' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/styleWith.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/UXCapture' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/uxCapture.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/UXCaptureCreate' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/uxCaptureCreate.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/UXCaptureFont' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/UXCaptureImageLoad' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/uxCaptureImageLoad.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/UXCaptureInlineMark' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/uxCaptureInlineMark.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/UXCaptureInteractiveMark' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/uxCaptureInteractiveMark.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/UXCaptureStartView' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/components/uxcapture/uxCaptureStartView.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/browserPolyfill' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/browserPolyfill.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/dateTimeUtils' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/dateTimeUtils.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/googleTagManager' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/googleTagManager.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/seo/ldJson' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/seo/ldJson.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/seo/links' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/seo/links.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/seo/metaTags' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/seo/metaTags.test' {
  declare module.exports: any;
}

declare module 'mwp-app-render/src/util/socialHelper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mwp-app-render/lib/components/BrowserApp.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/BrowserApp'>;
}
declare module 'mwp-app-render/lib/components/connectWithMatchMedia.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/connectWithMatchMedia'>;
}
declare module 'mwp-app-render/lib/components/Dom.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/Dom'>;
}
declare module 'mwp-app-render/lib/components/PageWrap/index.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/PageWrap/index'>;
}
declare module 'mwp-app-render/lib/components/SEOHead.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/SEOHead'>;
}
declare module 'mwp-app-render/lib/components/ServerApp.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/ServerApp'>;
}
declare module 'mwp-app-render/lib/components/shared/PlatformApp.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/shared/PlatformApp'>;
}
declare module 'mwp-app-render/lib/components/shared/ServiceWorker.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/shared/ServiceWorker'>;
}
declare module 'mwp-app-render/lib/components/StateBroadcast.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/StateBroadcast'>;
}
declare module 'mwp-app-render/lib/components/StyleWith.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/StyleWith'>;
}
declare module 'mwp-app-render/lib/components/uxcapture/UXCapture.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/uxcapture/UXCapture'>;
}
declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureCreate.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/uxcapture/UXCaptureCreate'>;
}
declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureFont.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/uxcapture/UXCaptureFont'>;
}
declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureImageLoad.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/uxcapture/UXCaptureImageLoad'>;
}
declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureInlineMark.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/uxcapture/UXCaptureInlineMark'>;
}
declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureInteractiveMark.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/uxcapture/UXCaptureInteractiveMark'>;
}
declare module 'mwp-app-render/lib/components/uxcapture/UXCaptureStartView.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/components/uxcapture/UXCaptureStartView'>;
}
declare module 'mwp-app-render/lib/util/browserPolyfill.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/util/browserPolyfill'>;
}
declare module 'mwp-app-render/lib/util/dateTimeUtils.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/util/dateTimeUtils'>;
}
declare module 'mwp-app-render/lib/util/googleTagManager.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/util/googleTagManager'>;
}
declare module 'mwp-app-render/lib/util/seo/ldJson.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/util/seo/ldJson'>;
}
declare module 'mwp-app-render/lib/util/seo/links.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/util/seo/links'>;
}
declare module 'mwp-app-render/lib/util/seo/metaTags.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/util/seo/metaTags'>;
}
declare module 'mwp-app-render/lib/util/socialHelper.js' {
  declare module.exports: $Exports<'mwp-app-render/lib/util/socialHelper'>;
}
declare module 'mwp-app-render/src/components/BrowserApp.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/BrowserApp'>;
}
declare module 'mwp-app-render/src/components/BrowserApp.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/BrowserApp.test'>;
}
declare module 'mwp-app-render/src/components/connectWithMatchMedia.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/connectWithMatchMedia'>;
}
declare module 'mwp-app-render/src/components/connectWithMatchMedia.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/connectWithMatchMedia.test'>;
}
declare module 'mwp-app-render/src/components/Dom.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/Dom'>;
}
declare module 'mwp-app-render/src/components/Dom.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/Dom.test'>;
}
declare module 'mwp-app-render/src/components/PageWrap/index.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/PageWrap/index'>;
}
declare module 'mwp-app-render/src/components/PageWrap/index.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/PageWrap/index.test'>;
}
declare module 'mwp-app-render/src/components/SEOHead.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/SEOHead'>;
}
declare module 'mwp-app-render/src/components/seoHead.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/seoHead.test'>;
}
declare module 'mwp-app-render/src/components/ServerApp.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/ServerApp'>;
}
declare module 'mwp-app-render/src/components/ServerApp.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/ServerApp.test'>;
}
declare module 'mwp-app-render/src/components/shared/PlatformApp.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/shared/PlatformApp'>;
}
declare module 'mwp-app-render/src/components/shared/ServiceWorker.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/shared/ServiceWorker'>;
}
declare module 'mwp-app-render/src/components/StateBroadcast.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/StateBroadcast'>;
}
declare module 'mwp-app-render/src/components/stateBroadcast.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/stateBroadcast.test'>;
}
declare module 'mwp-app-render/src/components/StyleWith.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/StyleWith'>;
}
declare module 'mwp-app-render/src/components/styleWith.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/styleWith.test'>;
}
declare module 'mwp-app-render/src/components/uxcapture/UXCapture.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/UXCapture'>;
}
declare module 'mwp-app-render/src/components/uxcapture/uxCapture.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/uxCapture.test'>;
}
declare module 'mwp-app-render/src/components/uxcapture/UXCaptureCreate.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/UXCaptureCreate'>;
}
declare module 'mwp-app-render/src/components/uxcapture/uxCaptureCreate.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/uxCaptureCreate.test'>;
}
declare module 'mwp-app-render/src/components/uxcapture/UXCaptureFont.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/UXCaptureFont'>;
}
declare module 'mwp-app-render/src/components/uxcapture/UXCaptureImageLoad.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/UXCaptureImageLoad'>;
}
declare module 'mwp-app-render/src/components/uxcapture/uxCaptureImageLoad.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/uxCaptureImageLoad.test'>;
}
declare module 'mwp-app-render/src/components/uxcapture/UXCaptureInlineMark.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/UXCaptureInlineMark'>;
}
declare module 'mwp-app-render/src/components/uxcapture/uxCaptureInlineMark.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/uxCaptureInlineMark.test'>;
}
declare module 'mwp-app-render/src/components/uxcapture/UXCaptureInteractiveMark.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/UXCaptureInteractiveMark'>;
}
declare module 'mwp-app-render/src/components/uxcapture/uxCaptureInteractiveMark.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/uxCaptureInteractiveMark.test'>;
}
declare module 'mwp-app-render/src/components/uxcapture/UXCaptureStartView.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/UXCaptureStartView'>;
}
declare module 'mwp-app-render/src/components/uxcapture/uxCaptureStartView.test.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/components/uxcapture/uxCaptureStartView.test'>;
}
declare module 'mwp-app-render/src/util/browserPolyfill.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/browserPolyfill'>;
}
declare module 'mwp-app-render/src/util/browserPolyfill.test.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/browserPolyfill.test'>;
}
declare module 'mwp-app-render/src/util/dateTimeUtils.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/dateTimeUtils'>;
}
declare module 'mwp-app-render/src/util/dateTimeUtils.test.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/dateTimeUtils.test'>;
}
declare module 'mwp-app-render/src/util/googleTagManager.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/googleTagManager'>;
}
declare module 'mwp-app-render/src/util/googleTagManager.test.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/googleTagManager.test'>;
}
declare module 'mwp-app-render/src/util/seo/ldJson.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/util/seo/ldJson'>;
}
declare module 'mwp-app-render/src/util/seo/ldJson.test.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/seo/ldJson.test'>;
}
declare module 'mwp-app-render/src/util/seo/links.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/seo/links'>;
}
declare module 'mwp-app-render/src/util/seo/links.test.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/seo/links.test'>;
}
declare module 'mwp-app-render/src/util/seo/metaTags.jsx' {
  declare module.exports: $Exports<'mwp-app-render/src/util/seo/metaTags'>;
}
declare module 'mwp-app-render/src/util/seo/metaTags.test.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/seo/metaTags.test'>;
}
declare module 'mwp-app-render/src/util/socialHelper.js' {
  declare module.exports: $Exports<'mwp-app-render/src/util/socialHelper'>;
}
