// flow-typed signature: c8dae5ddb84724015bdbbc613af7321b
// flow-typed version: <<STUB>>/react-flatpickr_v3.6.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-flatpickr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-flatpickr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-flatpickr/build/example' {
  declare module.exports: any;
}

declare module 'react-flatpickr/build/index' {
  declare module.exports: any;
}

declare module 'react-flatpickr/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-flatpickr/build/example.js' {
  declare module.exports: $Exports<'react-flatpickr/build/example'>;
}
declare module 'react-flatpickr/build/index.js' {
  declare module.exports: $Exports<'react-flatpickr/build/index'>;
}
declare module 'react-flatpickr/lib/index.js' {
  declare module.exports: $Exports<'react-flatpickr/lib/index'>;
}
