// flow-typed signature: 8d57a9fdb289639c587c80488eb35577
// flow-typed version: <<STUB>>/storybook-react-router_v1.0.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-react-router/dist/react' {
  declare module.exports: any;
}

declare module 'storybook-react-router/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-react-router/dist/react.js' {
  declare module.exports: $Exports<'storybook-react-router/dist/react'>;
}
declare module 'storybook-react-router/react.js' {
  declare module.exports: $Exports<'storybook-react-router/react'>;
}
