// flow-typed signature: 4187470a5021cff9feb47e295ebd4493
// flow-typed version: <<STUB>>/storybook-addon-i18n-tools_v1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-i18n-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-i18n-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-i18n-tools/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/dist/manager/components/SwapTextDirection/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/dist/manager/containers/Tools/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/dist/manager/containers/Tools/style' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/dist/manager/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/dist/preview/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/dist/shared/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/manager' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/preview' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/src/manager/components/SwapTextDirection/__tests__/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/src/manager/components/SwapTextDirection/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/src/manager/containers/Tools/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/src/manager/containers/Tools/style' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/src/manager/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/src/preview/__tests__/helpers/createMockChannel' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/src/preview/__tests__/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/src/preview/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n-tools/src/shared/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-i18n-tools/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/coverage/lcov-report/prettify'>;
}
declare module 'storybook-addon-i18n-tools/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/coverage/lcov-report/sorter'>;
}
declare module 'storybook-addon-i18n-tools/dist/manager/components/SwapTextDirection/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/dist/manager/components/SwapTextDirection/index'>;
}
declare module 'storybook-addon-i18n-tools/dist/manager/containers/Tools/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/dist/manager/containers/Tools/index'>;
}
declare module 'storybook-addon-i18n-tools/dist/manager/containers/Tools/style.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/dist/manager/containers/Tools/style'>;
}
declare module 'storybook-addon-i18n-tools/dist/manager/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/dist/manager/index'>;
}
declare module 'storybook-addon-i18n-tools/dist/preview/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/dist/preview/index'>;
}
declare module 'storybook-addon-i18n-tools/dist/shared/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/dist/shared/index'>;
}
declare module 'storybook-addon-i18n-tools/manager.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/manager'>;
}
declare module 'storybook-addon-i18n-tools/preview.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/preview'>;
}
declare module 'storybook-addon-i18n-tools/register.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/register'>;
}
declare module 'storybook-addon-i18n-tools/src/manager/components/SwapTextDirection/__tests__/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/src/manager/components/SwapTextDirection/__tests__/index'>;
}
declare module 'storybook-addon-i18n-tools/src/manager/components/SwapTextDirection/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/src/manager/components/SwapTextDirection/index'>;
}
declare module 'storybook-addon-i18n-tools/src/manager/containers/Tools/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/src/manager/containers/Tools/index'>;
}
declare module 'storybook-addon-i18n-tools/src/manager/containers/Tools/style.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/src/manager/containers/Tools/style'>;
}
declare module 'storybook-addon-i18n-tools/src/manager/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/src/manager/index'>;
}
declare module 'storybook-addon-i18n-tools/src/preview/__tests__/helpers/createMockChannel.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/src/preview/__tests__/helpers/createMockChannel'>;
}
declare module 'storybook-addon-i18n-tools/src/preview/__tests__/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/src/preview/__tests__/index'>;
}
declare module 'storybook-addon-i18n-tools/src/preview/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/src/preview/index'>;
}
declare module 'storybook-addon-i18n-tools/src/shared/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n-tools/src/shared/index'>;
}
