// flow-typed signature: 2e4b7f272e8c43667ab0377632b0d2be
// flow-typed version: <<STUB>>/swarm-icons_v^3.8.354/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swarm-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swarm-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swarm-icons/dist/js/shapeConstants' {
  declare module.exports: any;
}

declare module 'swarm-icons/Gruntfile' {
  declare module.exports: any;
}

declare module 'swarm-icons/scripts/exportFromSketch' {
  declare module.exports: any;
}

declare module 'swarm-icons/scripts/generateConstants' {
  declare module.exports: any;
}

declare module 'swarm-icons/scripts/util/sketchtoolUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swarm-icons/dist/js/shapeConstants.js' {
  declare module.exports: $Exports<'swarm-icons/dist/js/shapeConstants'>;
}
declare module 'swarm-icons/Gruntfile.js' {
  declare module.exports: $Exports<'swarm-icons/Gruntfile'>;
}
declare module 'swarm-icons/scripts/exportFromSketch.js' {
  declare module.exports: $Exports<'swarm-icons/scripts/exportFromSketch'>;
}
declare module 'swarm-icons/scripts/generateConstants.js' {
  declare module.exports: $Exports<'swarm-icons/scripts/generateConstants'>;
}
declare module 'swarm-icons/scripts/util/sketchtoolUtils.js' {
  declare module.exports: $Exports<'swarm-icons/scripts/util/sketchtoolUtils'>;
}
