// flow-typed signature: 30f1fc41c0c76edb7cf8a5585c67b864
// flow-typed version: <<STUB>>/swarm-constants_v1.2.94/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swarm-constants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swarm-constants' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swarm-constants/dist/js/colorAttributes' {
  declare module.exports: any;
}

declare module 'swarm-constants/dist/js/colorConstants' {
  declare module.exports: any;
}

declare module 'swarm-constants/dist/js/customProperties' {
  declare module.exports: any;
}

declare module 'swarm-constants/scripts/build' {
  declare module.exports: any;
}

declare module 'swarm-constants/scripts/formats' {
  declare module.exports: any;
}

declare module 'swarm-constants/scripts/transforms' {
  declare module.exports: any;
}

declare module 'swarm-constants/scripts/util/getRgbaString' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swarm-constants/dist/js/colorAttributes.js' {
  declare module.exports: $Exports<'swarm-constants/dist/js/colorAttributes'>;
}
declare module 'swarm-constants/dist/js/colorConstants.js' {
  declare module.exports: $Exports<'swarm-constants/dist/js/colorConstants'>;
}
declare module 'swarm-constants/dist/js/customProperties.js' {
  declare module.exports: $Exports<'swarm-constants/dist/js/customProperties'>;
}
declare module 'swarm-constants/scripts/build.js' {
  declare module.exports: $Exports<'swarm-constants/scripts/build'>;
}
declare module 'swarm-constants/scripts/formats.js' {
  declare module.exports: $Exports<'swarm-constants/scripts/formats'>;
}
declare module 'swarm-constants/scripts/transforms.js' {
  declare module.exports: $Exports<'swarm-constants/scripts/transforms'>;
}
declare module 'swarm-constants/scripts/util/getRgbaString.js' {
  declare module.exports: $Exports<'swarm-constants/scripts/util/getRgbaString'>;
}
