// flow-typed signature: 7fad7bd4d52262e3aca4ca9aeed412dd
// flow-typed version: <<STUB>>/swarm-sasstools_v^3.0.312/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swarm-sasstools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swarm-sasstools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swarm-sasstools/docs/templates/assets/pushy.min' {
  declare module.exports: any;
}

declare module 'swarm-sasstools/Gruntfile' {
  declare module.exports: any;
}

declare module 'swarm-sasstools/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swarm-sasstools/docs/templates/assets/pushy.min.js' {
  declare module.exports: $Exports<'swarm-sasstools/docs/templates/assets/pushy.min'>;
}
declare module 'swarm-sasstools/Gruntfile.js' {
  declare module.exports: $Exports<'swarm-sasstools/Gruntfile'>;
}
declare module 'swarm-sasstools/webpack.config.js' {
  declare module.exports: $Exports<'swarm-sasstools/webpack.config'>;
}
