// flow-typed signature: eca874c557749f1d9147a4704496a622
// flow-typed version: <<STUB>>/swarm-animation_v^0.0.95/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swarm-animation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swarm-animation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swarm-animation/dist/swarmAnimation' {
  declare module.exports: any;
}

declare module 'swarm-animation/docs/src/assets/pushy.min' {
  declare module.exports: any;
}

declare module 'swarm-animation/docs/src/js/docs' {
  declare module.exports: any;
}

declare module 'swarm-animation/GruntFile' {
  declare module.exports: any;
}

declare module 'swarm-animation/src/js/swarmAnimation' {
  declare module.exports: any;
}

declare module 'swarm-animation/test/specs/initial_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swarm-animation/dist/swarmAnimation.js' {
  declare module.exports: $Exports<'swarm-animation/dist/swarmAnimation'>;
}
declare module 'swarm-animation/docs/src/assets/pushy.min.js' {
  declare module.exports: $Exports<'swarm-animation/docs/src/assets/pushy.min'>;
}
declare module 'swarm-animation/docs/src/js/docs.js' {
  declare module.exports: $Exports<'swarm-animation/docs/src/js/docs'>;
}
declare module 'swarm-animation/GruntFile.js' {
  declare module.exports: $Exports<'swarm-animation/GruntFile'>;
}
declare module 'swarm-animation/src/js/swarmAnimation.js' {
  declare module.exports: $Exports<'swarm-animation/src/js/swarmAnimation'>;
}
declare module 'swarm-animation/test/specs/initial_spec.js' {
  declare module.exports: $Exports<'swarm-animation/test/specs/initial_spec'>;
}
