// flow-typed signature: 0c07d25554a9f552843d1a064cbf69dc
// flow-typed version: <<STUB>>/uri-js_v3.0.2/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uri-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uri-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uri-js/dist/es5/uri.all' {
  declare module.exports: any;
}

declare module 'uri-js/dist/es5/uri.all.min' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/index' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/regexps-iri' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/regexps-uri' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/schemes/http' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/schemes/https' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/schemes/mailto' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/schemes/urn-uuid' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/schemes/urn' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/uri' {
  declare module.exports: any;
}

declare module 'uri-js/dist/esnext/util' {
  declare module.exports: any;
}

declare module 'uri-js/rollup.config' {
  declare module.exports: any;
}

declare module 'uri-js/tests/qunit' {
  declare module.exports: any;
}

declare module 'uri-js/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uri-js/dist/es5/uri.all.js' {
  declare module.exports: $Exports<'uri-js/dist/es5/uri.all'>;
}
declare module 'uri-js/dist/es5/uri.all.min.js' {
  declare module.exports: $Exports<'uri-js/dist/es5/uri.all.min'>;
}
declare module 'uri-js/dist/esnext/index.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/index'>;
}
declare module 'uri-js/dist/esnext/regexps-iri.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/regexps-iri'>;
}
declare module 'uri-js/dist/esnext/regexps-uri.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/regexps-uri'>;
}
declare module 'uri-js/dist/esnext/schemes/http.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/schemes/http'>;
}
declare module 'uri-js/dist/esnext/schemes/https.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/schemes/https'>;
}
declare module 'uri-js/dist/esnext/schemes/mailto.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/schemes/mailto'>;
}
declare module 'uri-js/dist/esnext/schemes/urn-uuid.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/schemes/urn-uuid'>;
}
declare module 'uri-js/dist/esnext/schemes/urn.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/schemes/urn'>;
}
declare module 'uri-js/dist/esnext/uri.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/uri'>;
}
declare module 'uri-js/dist/esnext/util.js' {
  declare module.exports: $Exports<'uri-js/dist/esnext/util'>;
}
declare module 'uri-js/rollup.config.js' {
  declare module.exports: $Exports<'uri-js/rollup.config'>;
}
declare module 'uri-js/tests/qunit.js' {
  declare module.exports: $Exports<'uri-js/tests/qunit'>;
}
declare module 'uri-js/tests/tests.js' {
  declare module.exports: $Exports<'uri-js/tests/tests'>;
}
