// flow-typed signature: f65c18e0f74b88d2b450c0937f6e14f4
// flow-typed version: <<STUB>>/@js-joda/core_v1.12.0/flow_v0.101.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@js-joda/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@js-joda/core' {
	declare module.exports: any;
  }

  /**
   * We include stubs for each file inside this npm package in case you need to
   * require those files directly. Feel free to delete any files that aren't
   * needed.
   */
  declare module '@js-joda/core/dist/js-joda.esm' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/dist/js-joda.flow' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/dist/js-joda' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/dist/js-joda.min' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/_init' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/assert' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/chrono/ChronoLocalDate' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/chrono/ChronoLocalDateTime' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/chrono/ChronoZonedDateTime' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/chrono/IsoChronology' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/Clock' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/convert' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/DayOfWeek' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/Duration' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/Enum' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/errors' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/DateTimeBuilder' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/DateTimeFormatter' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/DateTimeFormatterBuilder' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/DateTimeParseContext' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/DateTimePrintContext' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/DecimalStyle' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/EnumMap' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/ParsePosition' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/parser/CharLiteralPrinterParser' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/parser/CompositePrinterParser' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/parser/FractionPrinterParser' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/parser/NumberPrinterParser' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/parser/OffsetIdPrinterParser' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/parser/PadPrinterParserDecorator' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/parser/SettingsParser' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/parser/StringLiteralPrinterParser' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/parser/ZoneIdPrinterParser' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/ResolverStyle' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/SignStyle' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/StringBuilder' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/format/TextStyle' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/Instant' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/js-joda' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/license-preamble' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/LocalDate' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/LocalDateTime' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/LocalTime' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/MathUtil' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/Month' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/MonthDay' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/Period' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/StringUtil' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/ChronoField' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/ChronoUnit' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/IsoFields' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/NativeJsTemporal' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/Temporal' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/TemporalAccessor' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/TemporalAdjuster' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/TemporalAdjusters' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/TemporalAmount' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/TemporalField' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/TemporalQueries' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/TemporalQueriesFactory' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/TemporalQuery' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/TemporalUnit' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/temporal/ValueRange' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/use' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/Year' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/YearConstants' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/YearMonth' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/zone/SystemDefaultZoneId' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/zone/SystemDefaultZoneRules' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/zone/ZoneOffsetTransition' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/zone/ZoneRules' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/zone/ZoneRulesProvider' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/ZonedDateTime' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/ZoneId' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/ZoneIdFactory' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/ZoneOffset' {
	declare module.exports: any;
  }

  declare module '@js-joda/core/src/ZoneRegion' {
	declare module.exports: any;
  }

  // Filename aliases
  declare module '@js-joda/core/dist/js-joda.esm.js' {
	declare module.exports: $Exports<'@js-joda/core/dist/js-joda.esm'>;
  }
  declare module '@js-joda/core/dist/js-joda.flow.js' {
	declare module.exports: $Exports<'@js-joda/core/dist/js-joda.flow'>;
  }
  declare module '@js-joda/core/dist/js-joda.js' {
	declare module.exports: $Exports<'@js-joda/core/dist/js-joda'>;
  }
  declare module '@js-joda/core/dist/js-joda.min.js' {
	declare module.exports: $Exports<'@js-joda/core/dist/js-joda.min'>;
  }
  declare module '@js-joda/core/src/_init.js' {
	declare module.exports: $Exports<'@js-joda/core/src/_init'>;
  }
  declare module '@js-joda/core/src/assert.js' {
	declare module.exports: $Exports<'@js-joda/core/src/assert'>;
  }
  declare module '@js-joda/core/src/chrono/ChronoLocalDate.js' {
	declare module.exports: $Exports<'@js-joda/core/src/chrono/ChronoLocalDate'>;
  }
  declare module '@js-joda/core/src/chrono/ChronoLocalDateTime.js' {
	declare module.exports: $Exports<'@js-joda/core/src/chrono/ChronoLocalDateTime'>;
  }
  declare module '@js-joda/core/src/chrono/ChronoZonedDateTime.js' {
	declare module.exports: $Exports<'@js-joda/core/src/chrono/ChronoZonedDateTime'>;
  }
  declare module '@js-joda/core/src/chrono/IsoChronology.js' {
	declare module.exports: $Exports<'@js-joda/core/src/chrono/IsoChronology'>;
  }
  declare module '@js-joda/core/src/Clock.js' {
	declare module.exports: $Exports<'@js-joda/core/src/Clock'>;
  }
  declare module '@js-joda/core/src/convert.js' {
	declare module.exports: $Exports<'@js-joda/core/src/convert'>;
  }
  declare module '@js-joda/core/src/DayOfWeek.js' {
	declare module.exports: $Exports<'@js-joda/core/src/DayOfWeek'>;
  }
  declare module '@js-joda/core/src/Duration.js' {
	declare module.exports: $Exports<'@js-joda/core/src/Duration'>;
  }
  declare module '@js-joda/core/src/Enum.js' {
	declare module.exports: $Exports<'@js-joda/core/src/Enum'>;
  }
  declare module '@js-joda/core/src/errors.js' {
	declare module.exports: $Exports<'@js-joda/core/src/errors'>;
  }
  declare module '@js-joda/core/src/format/DateTimeBuilder.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/DateTimeBuilder'>;
  }
  declare module '@js-joda/core/src/format/DateTimeFormatter.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/DateTimeFormatter'>;
  }
  declare module '@js-joda/core/src/format/DateTimeFormatterBuilder.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/DateTimeFormatterBuilder'>;
  }
  declare module '@js-joda/core/src/format/DateTimeParseContext.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/DateTimeParseContext'>;
  }
  declare module '@js-joda/core/src/format/DateTimePrintContext.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/DateTimePrintContext'>;
  }
  declare module '@js-joda/core/src/format/DecimalStyle.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/DecimalStyle'>;
  }
  declare module '@js-joda/core/src/format/EnumMap.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/EnumMap'>;
  }
  declare module '@js-joda/core/src/format/ParsePosition.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/ParsePosition'>;
  }
  declare module '@js-joda/core/src/format/parser/CharLiteralPrinterParser.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/parser/CharLiteralPrinterParser'>;
  }
  declare module '@js-joda/core/src/format/parser/CompositePrinterParser.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/parser/CompositePrinterParser'>;
  }
  declare module '@js-joda/core/src/format/parser/FractionPrinterParser.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/parser/FractionPrinterParser'>;
  }
  declare module '@js-joda/core/src/format/parser/NumberPrinterParser.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/parser/NumberPrinterParser'>;
  }
  declare module '@js-joda/core/src/format/parser/OffsetIdPrinterParser.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/parser/OffsetIdPrinterParser'>;
  }
  declare module '@js-joda/core/src/format/parser/PadPrinterParserDecorator.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/parser/PadPrinterParserDecorator'>;
  }
  declare module '@js-joda/core/src/format/parser/SettingsParser.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/parser/SettingsParser'>;
  }
  declare module '@js-joda/core/src/format/parser/StringLiteralPrinterParser.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/parser/StringLiteralPrinterParser'>;
  }
  declare module '@js-joda/core/src/format/parser/ZoneIdPrinterParser.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/parser/ZoneIdPrinterParser'>;
  }
  declare module '@js-joda/core/src/format/ResolverStyle.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/ResolverStyle'>;
  }
  declare module '@js-joda/core/src/format/SignStyle.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/SignStyle'>;
  }
  declare module '@js-joda/core/src/format/StringBuilder.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/StringBuilder'>;
  }
  declare module '@js-joda/core/src/format/TextStyle.js' {
	declare module.exports: $Exports<'@js-joda/core/src/format/TextStyle'>;
  }
  declare module '@js-joda/core/src/Instant.js' {
	declare module.exports: $Exports<'@js-joda/core/src/Instant'>;
  }
  declare module '@js-joda/core/src/js-joda.js' {
	declare module.exports: $Exports<'@js-joda/core/src/js-joda'>;
  }
  declare module '@js-joda/core/src/license-preamble.js' {
	declare module.exports: $Exports<'@js-joda/core/src/license-preamble'>;
  }
  declare module '@js-joda/core/src/LocalDate.js' {
	declare module.exports: $Exports<'@js-joda/core/src/LocalDate'>;
  }
  declare module '@js-joda/core/src/LocalDateTime.js' {
	declare module.exports: $Exports<'@js-joda/core/src/LocalDateTime'>;
  }
  declare module '@js-joda/core/src/LocalTime.js' {
	declare module.exports: $Exports<'@js-joda/core/src/LocalTime'>;
  }
  declare module '@js-joda/core/src/MathUtil.js' {
	declare module.exports: $Exports<'@js-joda/core/src/MathUtil'>;
  }
  declare module '@js-joda/core/src/Month.js' {
	declare module.exports: $Exports<'@js-joda/core/src/Month'>;
  }
  declare module '@js-joda/core/src/MonthDay.js' {
	declare module.exports: $Exports<'@js-joda/core/src/MonthDay'>;
  }
  declare module '@js-joda/core/src/Period.js' {
	declare module.exports: $Exports<'@js-joda/core/src/Period'>;
  }
  declare module '@js-joda/core/src/StringUtil.js' {
	declare module.exports: $Exports<'@js-joda/core/src/StringUtil'>;
  }
  declare module '@js-joda/core/src/temporal/ChronoField.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/ChronoField'>;
  }
  declare module '@js-joda/core/src/temporal/ChronoUnit.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/ChronoUnit'>;
  }
  declare module '@js-joda/core/src/temporal/IsoFields.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/IsoFields'>;
  }
  declare module '@js-joda/core/src/temporal/NativeJsTemporal.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/NativeJsTemporal'>;
  }
  declare module '@js-joda/core/src/temporal/Temporal.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/Temporal'>;
  }
  declare module '@js-joda/core/src/temporal/TemporalAccessor.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/TemporalAccessor'>;
  }
  declare module '@js-joda/core/src/temporal/TemporalAdjuster.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/TemporalAdjuster'>;
  }
  declare module '@js-joda/core/src/temporal/TemporalAdjusters.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/TemporalAdjusters'>;
  }
  declare module '@js-joda/core/src/temporal/TemporalAmount.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/TemporalAmount'>;
  }
  declare module '@js-joda/core/src/temporal/TemporalField.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/TemporalField'>;
  }
  declare module '@js-joda/core/src/temporal/TemporalQueries.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/TemporalQueries'>;
  }
  declare module '@js-joda/core/src/temporal/TemporalQueriesFactory.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/TemporalQueriesFactory'>;
  }
  declare module '@js-joda/core/src/temporal/TemporalQuery.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/TemporalQuery'>;
  }
  declare module '@js-joda/core/src/temporal/TemporalUnit.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/TemporalUnit'>;
  }
  declare module '@js-joda/core/src/temporal/ValueRange.js' {
	declare module.exports: $Exports<'@js-joda/core/src/temporal/ValueRange'>;
  }
  declare module '@js-joda/core/src/use.js' {
	declare module.exports: $Exports<'@js-joda/core/src/use'>;
  }
  declare module '@js-joda/core/src/Year.js' {
	declare module.exports: $Exports<'@js-joda/core/src/Year'>;
  }
  declare module '@js-joda/core/src/YearConstants.js' {
	declare module.exports: $Exports<'@js-joda/core/src/YearConstants'>;
  }
  declare module '@js-joda/core/src/YearMonth.js' {
	declare module.exports: $Exports<'@js-joda/core/src/YearMonth'>;
  }
  declare module '@js-joda/core/src/zone/SystemDefaultZoneId.js' {
	declare module.exports: $Exports<'@js-joda/core/src/zone/SystemDefaultZoneId'>;
  }
  declare module '@js-joda/core/src/zone/SystemDefaultZoneRules.js' {
	declare module.exports: $Exports<'@js-joda/core/src/zone/SystemDefaultZoneRules'>;
  }
  declare module '@js-joda/core/src/zone/ZoneOffsetTransition.js' {
	declare module.exports: $Exports<'@js-joda/core/src/zone/ZoneOffsetTransition'>;
  }
  declare module '@js-joda/core/src/zone/ZoneRules.js' {
	declare module.exports: $Exports<'@js-joda/core/src/zone/ZoneRules'>;
  }
  declare module '@js-joda/core/src/zone/ZoneRulesProvider.js' {
	declare module.exports: $Exports<'@js-joda/core/src/zone/ZoneRulesProvider'>;
  }
  declare module '@js-joda/core/src/ZonedDateTime.js' {
	declare module.exports: $Exports<'@js-joda/core/src/ZonedDateTime'>;
  }
  declare module '@js-joda/core/src/ZoneId.js' {
	declare module.exports: $Exports<'@js-joda/core/src/ZoneId'>;
  }
  declare module '@js-joda/core/src/ZoneIdFactory.js' {
	declare module.exports: $Exports<'@js-joda/core/src/ZoneIdFactory'>;
  }
  declare module '@js-joda/core/src/ZoneOffset.js' {
	declare module.exports: $Exports<'@js-joda/core/src/ZoneOffset'>;
  }
  declare module '@js-joda/core/src/ZoneRegion.js' {
	declare module.exports: $Exports<'@js-joda/core/src/ZoneRegion'>;
  }
