// flow-typed signature: febad60289e1b817e6fddff33cc021b8
// flow-typed version: <<STUB>>/@alrra/travis-scripts_v3.0.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@alrra/travis-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@alrra/travis-scripts' {
  declare module.exports: any;
}
